org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
systemProp.org.gradle.internal.http.socketTimeout=120000
systemProp.org.gradle.internal.http.connectionTimeout=120000

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.97

# Mod Properties
mod_id=simpleautofarm
mod_name=Simple Auto Farm
mod_license=MIT
mod_version=1.2.0
mod_group_id=com.simpleautofarm
mod_authors=EasyRain
mod_description=A simple automatic farm machine for NeoForge 26.1.2.
